"""initial_schema

Revision ID: 7b1c2b825c38
Revises: 
Create Date: 2026-09-10 14:05:37.101064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1c2b825c38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('danger_level_meters', sa.Float(), nullable=False),
    sa.Column('warning_level_meters', sa.Float(), nullable=False),
    sa.Column('gauge_station', sa.String(length=100), nullable=True),
    sa.Column('basin', sa.String(length=100), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('has_medical', sa.Boolean(), nullable=False),
    sa.Column('has_power_backup', sa.Boolean(), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('current_substep', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('speed_multiplier', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('villages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tehsil', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('distance_to_river', sa.Float(), nullable=False),
    sa.Column('historical_flood_frequency', sa.Float(), nullable=False),
    sa.Column('vulnerability_index', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.create_table('environmental_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('village_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rainfall_1h', sa.Float(), nullable=False),
    sa.Column('rainfall_3h', sa.Float(), nullable=False),
    sa.Column('rainfall_6h', sa.Float(), nullable=False),
    sa.Column('rainfall_24h', sa.Float(), nullable=False),
    sa.Column('rainfall_intensity', sa.Float(), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('river_level', sa.Float(), nullable=False),
    sa.Column('river_level_change', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_obs_village_timestamp', 'environmental_observations', ['village_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_environmental_observations_village_id'), 'environmental_observations', ['village_id'], unique=False)
    op.create_table('risk_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('village_id', sa.String(length=36), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_id')
    )
    op.create_table('routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('origin_village_id', sa.String(length=36), nullable=False),
    sa.Column('destination_shelter_id', sa.String(length=36), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('assessed_risk_score', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blockage_reason', sa.String(length=255), nullable=True),
    sa.Column('is_river_crossing', sa.Boolean(), nullable=False),
    sa.Column('crossing_coordinates', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_shelter_id'], ['shelters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('village_id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('flood_probability', sa.Float(), nullable=False),
    sa.Column('prediction_quality', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('feature_contributions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['environmental_observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_village_id'), 'predictions', ['village_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('village_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('trigger_reason', sa.String(length=500), nullable=False),
    sa.Column('top_contributors', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=180), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_status_severity', 'alerts', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_village_id'), 'alerts', ['village_id'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('village_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_village_time', 'risk_snapshots', ['village_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_risk_snapshots_village_id'), 'risk_snapshots', ['village_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_snapshots_village_id'), table_name='risk_snapshots')
    op.drop_index('idx_snapshot_village_time', table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index(op.f('ix_alerts_village_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index('idx_alert_status_severity', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_predictions_village_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('routes')
    op.drop_table('risk_zones')
    op.drop_index(op.f('ix_environmental_observations_village_id'), table_name='environmental_observations')
    op.drop_index('idx_obs_village_timestamp', table_name='environmental_observations')
    op.drop_table('environmental_observations')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('simulations')
    op.drop_table('shelters')
    op.drop_table('rivers')
    # ### end Alembic commands ###
